CREATE TABLE resources (
    id VARCHAR(255) PRIMARY KEY,
    filename VARCHAR(255),
    url VARCHAR(255),
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)