# Start from the official Go image
FROM golang:1.19-alpine

# Set environment variables
ENV GO111MODULE=on

# Install dependencies and golang-migrate
RUN apk add --no-cache curl \
    && curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.0/migrate.linux-amd64.tar.gz | tar xvz -C /usr/local/bin \
    && chmod +x /usr/local/bin/migrate

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to the container
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the entire source code to the container
COPY . .

# Build the Go application
RUN go build -o main .

# Expose the port the app will run on
EXPOSE 8080

# Run migrations and start the application
CMD migrate -database ${DB_URL} -path ./migrations up && ./main
